### PR TITLE
Disable nonworking menus

### LINKED ISSUE #25: non-working functionality is exposed in Aardvark
This will be confusing for users, though maybe good for developers.  Need to disable in the release for now.
* interfaces menu
* Configuration and both submenus
* gpio -> blinky
* i2c -> edit
* renesas -> BuzyBox

### PR DESCRIPTION
**Pull request by jrhunger**
Fixes #25 
Some of the fixes can be done in Aardvark, but others have to be done in Ant thanks to the get menu feature.

### CODE REVIEW

**Comment by jrhunger** [comment]
Note, the Renesas -> Read File was left because while it doesn't have a dialog to load a file from the device, it does have a matrix which can be edited, and the FLASH RAM button makes a bunch of i2c rest calls to the device.  Implying i guess that the matrix could be hand-edited?

**Comment by petesoper** [comment]
From memory the Renesas read file operation doesn't have any specific dialog for the file chosing. One just has to know that dragging and dropping from a file navigator causes the file to be handled. I've confirmed this appears to work, but what no longer works is a transfer from the downloaded file into the FPGA matrix/spreadsheet. Disabling the load file temporarily is best, in my opinion.

Also, conditional execution const bools in the javascript file with some comments are called for.

**Comment by petesoper** [comment]
You've convinced me about leaving the read file function in place. 
Only installing curl is going to set up a lot of folks for heartache. In my opinion it's a mistake to not install the prerequisite packages. Remind me of the rationale for this?
I read all the Vue changes with the merest hint of understanding. Testing the code now while waiting for your reply.

**Comment by petesoper** [comment]
With the documentation for the toggle it should be pointed out that putting the toggle back to "hidden" will not cause menus to disappear.
There is something that causes the "not hidden" state to be remembered across Aardvark executions. To reproduce:
1. Start node
2. Point browser to localhost:8080
3. Switch the "show hidden components" to "on"
4. Delete the browser tab and point a tab again to localhost:8080
5. The menus are still in the state of "show hidden".

**Comment by petesoper** [comment]
Forgot this PR! Sorry.

**Pull request merged**
